#! /bin/sh

bspc config border_width 4
bspc config window_gap 0
bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config focused_border_color "#ff00ff"
bspc config normal_border_color "#181818"
bspc config single_monocle true
bspc monitor HDMI-0 -d 1 2 3
bspc monitor DP-2 -d 4 5 6
bspc monitor DP-0 -d 7 8 9
xsetroot -cursor_name left_ptr &

bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config external_rules_command "/home/dank/.config/bspwm/down_center_scheme"

polybar monitor1 &
polybar monitor2 &
polybar monitor3 &
